branches:
    only:
        - master
environment:
    matrix:
        - BUILD_SHARED_LIBS: ON
        - BUILD_SHARED_LIBS: OFF
matrix:
    fast_finish: true
build_script:
    - mkdir build
    - cd build
    - cmake ..
    - cmake --build .